--1)
select * from user_tables;

--2)
--a) A chave de indexação é NOME. Ela é única e o índice é PK_Time.

--b)
EXEC DBMS_STATS.GATHER_SCHEMA_STATS(NULL, NULL);

--c)
-- Caso 1
EXPLAIN PLAN FOR
select * from time where nome = 'INTER';
SELECT plan_table_output
    FROM TABLE(dbms_xplan.display());

-- Caso 2
EXPLAIN PLAN FOR
select * from time where upper(nome) = 'INTER';
SELECT plan_table_output
    FROM TABLE(dbms_xplan.display());

-- Caso 3
EXPLAIN PLAN FOR
select * from time where nome like 'IN%';
SELECT plan_table_output
    FROM TABLE(dbms_xplan.display());
    
--Caso 4
EXPLAIN PLAN FOR
select * from time where nome like '%TER';
SELECT plan_table_output
    FROM TABLE(dbms_xplan.display());
    
--Exs:
--1)
SELECT TIME1, TIME2, DATA 
FROM PARTIDA
WHERE LOCAL = 'SANTOS';

--2)
SELECT DATA, LOCAL
FROM PARTIDA
WHERE TIME1 = 'PALMEIRAS' OR TIME2 = 'PALMEIRAS';

-- Formatando para Dia/Mês/Ano e Hora:Minuto
SELECT to_char(data, 'DD/MM/YYYY HH24:MI') as data_formatada, local
FROM Partida
WHERE time1 = 'PALMEIRAS' OR time2 = 'PALMEIRAS';

--Porque o tipo de atributo DATE usa a formatação de apresentação padrão do Oracle, que oculta o horário

--3)
SELECT *
FROM JOGADOR J, TIME T;

SELECT *
FROM JOGADOR J, TIME T
WHERE J.TIME = T.NOME;

SELECT J.CPF, J.NOME, TRUNC((SYSDATE - J.DATA_NASC)/365.25) AS IDADE, T.NOME, T.ESTADO
FROM JOGADOR J, TIME T
WHERE J.TIME = T.NOME;

--4)
SELECT J.CPF, J.NOME, J.DATA_NASC, T.NOME
FROM JOGADOR J, TIME T
WHERE J.TIME = T.NOME AND T.ESTADO = 'SP';

SELECT J.CPF, J.NOME, J.DATA_NASC, T.NOME
FROM JOGADOR J
JOIN TIME T ON J.TIME = T.NOME
WHERE T.ESTADO = 'SP';

--5)
SELECT P.TIME1, P.TIME2, P.DATA, P.PLACAR, J.CLASSICO
FROM PARTIDA P
JOIN JOGA J ON J.TIME1 = P.TIME1 AND J.TIME2 = P.TIME2
WHERE P.LOCAL = 'SANTOS';

--6)
SELECT T1.NOME AS NOME_TIME1, T1.ESTADO AS ESTADO_TIME1, T2.NOME AS NOME_TIME2, T2.ESTADO AS ESTADO_TIME2
FROM JOGA J
JOIN TIME T1 ON J.TIME1 = T1.NOME
JOIN TIME T2 ON J.TIME2 = T2.NOME
WHERE J.CLASSICO = 'S';

--7)
SELECT T.NOME, U.COR_PRINCIPAL
FROM TIME T
JOIN UNIFORME U ON T.NOME = U.TIME AND U.TIPO = 'TITULAR'
WHERE T.TIPO = 'PROFISSIONAL' AND T.ESTADO = 'MG';

--8)
SELECT DISTINCT P.TIME1, P.TIME2,P.DATA, P.PLACAR,P.LOCAL
FROM PARTIDA P
WHERE EXISTS(
    SELECT 1
    FROM TIME T
    WHERE T.ESTADO = 'SP' AND (T.NOME = P.TIME1 OR T.NOME = P.TIME2)
);

--9)
SELECT T.NOME, T.ESTADO, T.TIPO, T.SALDO_GOLS
FROM TIME T 
WHERE NOT EXISTS (
    SELECT 1
    FROM PARTIDA P
    WHERE (P.TIME1 = T.NOME OR P.TIME2 = T.NOME)
    AND P.LOCAL IN ('SAO CARLOS', 'BELO HORIZONTE') 
);

--10)
SELECT T.NOME, T.ESTADO
FROM TIME T
JOIN UNIFORME U ON U.TIME = T.NOME
WHERE U.COR_PRINCIPAL IS NULL AND U.TIPO = 'TITULAR';

--11)
SELECT 
    J.NOME, 
    J.DATA_NASC, 
    J.TIME, 
    MIN(P.DATA) AS DATA_ESTREIA,
    MIN(P.LOCAL) KEEP (DENSE_RANK FIRST ORDER BY P.DATA ASC) AS LOCAL_ESTREIA,
    MIN(JG.CLASSICO) KEEP (DENSE_RANK FIRST ORDER BY P.DATA ASC) AS ESTREIA_FOI_CLASSICO
FROM JOGADOR J
JOIN PARTIDA P ON P.TIME1 = J.TIME OR P.TIME2 = J.TIME
JOIN JOGA JG ON P.TIME1 = JG.TIME1 AND P.TIME2 = JG.TIME2
GROUP BY (J.NOME, J.DATA_NASC, J.TIME);

--12)
SELECT T.NOME, T.ESTADO, D.NOME
FROM TIME T
LEFT JOIN DIRETOR D ON D.TIME = T.NOME;

--13)