--Faz uma lista de comandos de drop
select 'drop table ' ||table_name||' cascade constraints;' from user_tables; 

--Drop all
drop table DIRETOR cascade constraints;
drop table JOGA cascade constraints;
drop table JOGADOR cascade constraints;
drop table PARTIDA cascade constraints;
drop table POSICAO_JOGADOR cascade constraints;
drop table TIME cascade constraints;
drop table UNIFORME cascade constraints;

EXEC DBMS_STATS.GATHER_SCHEMA_STATS(NULL, NULL); 

-- Caso 1 
EXPLAIN PLAN FOR 
select * from time where nome = 'INTER';  
SELECT plan_table_output FROM TABLE(dbms_xplan.display()); 

-- Caso 2 
EXPLAIN PLAN FOR 
select * from time where upper(nome) = 'INTER';  
SELECT plan_table_output FROM TABLE(dbms_xplan.display()); 

-- Caso 3 
EXPLAIN PLAN FOR 
select * from time where nome like 'IN%';  
SELECT plan_table_output FROM TABLE(dbms_xplan.display()); 

-- Caso 4 
EXPLAIN PLAN FOR 
select * from time where nome like '%TER';  
SELECT plan_table_output FROM TABLE(dbms_xplan.display()); 

--Ex 1
select time1, time2, data from partida where time2 = (select nome from time where upper(nome) = 'SANTOS');

--Inserts novos
INSERT INTO TIME VALUES ('GREMIO', 'RS', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CORINTHIANS', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SAO PAULO', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('BAHIA', 'BA', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('VITORIA', 'BA', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SPORT', 'PE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('NAUTICO', 'PE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SANTA CRUZ', 'PE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('FORTALEZA', 'CE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CEARA', 'CE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('PAYSANDU', 'PA', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('REMO', 'PA', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('GOIAS', 'GO', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('ATLETICO GO', 'GO', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CUIABA', 'MT', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('OPERARIO', 'PR', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CORITIBA', 'PR', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('ATHLETICO', 'PR', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('JUVENTUDE', 'RS', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('AMERICA MG', 'MG', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('BRAGANTINO', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('ITUANO', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('PONTE PRETA', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('GUARANI', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('ABC', 'RN', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('AMERICA RN', 'RN', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CRB', 'AL', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('CSA', 'AL', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('FERROVIARIO', 'CE', 'AMADOR', 0);
INSERT INTO TIME VALUES ('JUAZEIRENSE', 'BA', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BOA ESPORTE', 'MG', 'AMADOR', 0);
INSERT INTO TIME VALUES ('TOMBENSE', 'MG', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BRUSQUE', 'SC', 'AMADOR', 0);
INSERT INTO TIME VALUES ('JOINVILLE', 'SC', 'AMADOR', 0);
INSERT INTO TIME VALUES ('FIGUEIRENSE', 'SC', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('PARANA', 'PR', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('LONDRINA', 'PR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MIRASSOL', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('NOVORIZONTINO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('XV DE PIRACICABA', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('SANTO ANDRE', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('SAO BENTO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('VOLTA REDONDA', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('AMERICA RJ', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CABOFRIENSE', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MACAE', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BANGU', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('PORTUGUESA RJ', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BRASIL DE PELOTAS', 'RS', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CAXIAS', 'RS', 'AMADOR', 0);
INSERT INTO TIME VALUES ('PELOTAS', 'RS', 'AMADOR', 0);
INSERT INTO TIME VALUES ('Y-PIRANGA', 'RS', 'AMADOR', 0);
INSERT INTO TIME VALUES ('NOVA IGUACU', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RESENDE', 'RJ', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RIO BRANCO', 'AC', 'AMADOR', 0);
INSERT INTO TIME VALUES ('FAST CLUB', 'AM', 'AMADOR', 0);
INSERT INTO TIME VALUES ('NACIONAL AM', 'AM', 'AMADOR', 0);
INSERT INTO TIME VALUES ('PENAROL AM', 'AM', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MANAUS', 'AM', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SAO RAIMUNDO', 'RR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RORAIMA FC', 'RR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('TREZE', 'PB', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CAMPINENSE', 'PB', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BOTAFOGO PB', 'PB', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SERRANO', 'PB', 'AMADOR', 0);
INSERT INTO TIME VALUES ('ICASA', 'CE', 'AMADOR', 0);
INSERT INTO TIME VALUES ('GUARANY DE SOBRAL', 'CE', 'AMADOR', 0);
INSERT INTO TIME VALUES ('TIRADENTES CE', 'CE', 'AMADOR', 0);
INSERT INTO TIME VALUES ('ASA', 'AL', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MURICI', 'AL', 'AMADOR', 0);
INSERT INTO TIME VALUES ('JUAZEIRO', 'BA', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CONFIANCA', 'SE', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('SERGIPE', 'SE', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BARRAS', 'PI', 'AMADOR', 0);
INSERT INTO TIME VALUES ('FLAMENGO PI', 'PI', 'AMADOR', 0);
INSERT INTO TIME VALUES ('PARNahyba', 'PI', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RIO NEGRO', 'AM', 'AMADOR', 0);
INSERT INTO TIME VALUES ('LUZIANIA', 'GO', 'AMADOR', 0);
INSERT INTO TIME VALUES ('VILA NOVA', 'GO', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('BRASILIA', 'DF', 'AMADOR', 0);
INSERT INTO TIME VALUES ('GAMA', 'DF', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BRASILIENSE', 'DF', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('REAL BRASÍLIA', 'DF', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RIO PRETO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('TAUBATE', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('FERROVIARIA', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('RED BULL BRASIL', 'SP', 'PROFISSIONAL', 0);
INSERT INTO TIME VALUES ('BARUERI', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CASCAVEL', 'PR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MARINGA', 'PR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('APUCARANA', 'PR', 'AMADOR', 0);
INSERT INTO TIME VALUES ('RIO CLARO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('CATANDUVA', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('SOROCABA', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('OSASCO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('TABOAO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('SERTAOZINHO', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('MONTE AZUL', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('BARRETOS', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('FRANCA', 'SP', 'AMADOR', 0);
INSERT INTO TIME VALUES ('ASSISENSE', 'SP', 'AMADOR', 0);

INSERT INTO JOGA VALUES ('PALMEIRAS', 'CORINTHIANS', 'S');
INSERT INTO JOGA VALUES ('PALMEIRAS', 'SAO PAULO', 'S');
INSERT INTO JOGA VALUES ('FLAMENGO', 'BOTAFOGO', 'S');
INSERT INTO JOGA VALUES ('FLAMENGO', 'VASCO', 'S');
INSERT INTO JOGA VALUES ('GREMIO', 'INTERNACIONAL', 'S');
INSERT INTO JOGA VALUES ('ATLETICO', 'CRUZEIRO', 'S');
INSERT INTO JOGA VALUES ('SANTOS', 'CORINTHIANS', 'S');
INSERT INTO JOGA VALUES ('SANTOS', 'SAO PAULO', 'S');
INSERT INTO JOGA VALUES ('BAHIA', 'VITORIA', 'S');
INSERT INTO JOGA VALUES ('SPORT', 'NAUTICO', 'S');
INSERT INTO JOGA VALUES ('SPORT', 'SANTA CRUZ', 'S');
INSERT INTO JOGA VALUES ('CORITIBA', 'ATHLETICO', 'S');
INSERT INTO JOGA VALUES ('JUVENTUDE', 'GREMIO', 'N');
INSERT INTO JOGA VALUES ('GOIAS', 'ATLETICO GO', 'S');
INSERT INTO JOGA VALUES ('FORTALEZA', 'CEARA', 'S');
INSERT INTO JOGA VALUES ('PAYSANDU', 'REMO', 'S');
INSERT INTO JOGA VALUES ('AMERICA MG', 'CRUZEIRO', 'N');
INSERT INTO JOGA VALUES ('BRAGANTINO', 'PALMEIRAS', 'N');
INSERT INTO JOGA VALUES ('PONTE PRETA', 'GUARANI', 'S');
INSERT INTO JOGA VALUES ('FIGUEIRENSE', 'CHAPECOENSE', 'S');
INSERT INTO JOGA VALUES ('CORITIBA', 'PARANA', 'S');
INSERT INTO JOGA VALUES ('ITUANO', 'MIRASSOL', 'N');
INSERT INTO JOGA VALUES ('RED BULL BRASIL', 'BRAGANTINO', 'N');
INSERT INTO JOGA VALUES ('FERROVIARIA', 'ITUANO', 'N');
INSERT INTO JOGA VALUES ('AMERICA RJ', 'BANGU', 'S');
INSERT INTO JOGA VALUES ('AMERICA RJ', 'CABOFRIENSE', 'N');
INSERT INTO JOGA VALUES ('VOLTA REDONDA', 'MACAE', 'N');
INSERT INTO JOGA VALUES ('JUAZEIRENSE', 'BAHIA', 'N');
INSERT INTO JOGA VALUES ('JUAZEIRENSE', 'VITORIA', 'N');
INSERT INTO JOGA VALUES ('CSA', 'CRB', 'S');
INSERT INTO JOGA VALUES ('ABC', 'AMERICA RN', 'S');
INSERT INTO JOGA VALUES ('CONFIANCA', 'SERGIPE', 'S');
INSERT INTO JOGA VALUES ('BOTAFOGO PB', 'CAMPINENSE', 'S');
INSERT INTO JOGA VALUES ('LUZIANIA', 'VILA NOVA', 'N');
INSERT INTO JOGA VALUES ('BRASILIENSE', 'GAMA', 'S');
INSERT INTO JOGA VALUES ('GOIAS', 'VILA NOVA', 'S');
INSERT INTO JOGA VALUES ('PONTE PRETA', 'SAO PAULO', 'N');
INSERT INTO JOGA VALUES ('PALMEIRAS', 'BRAGANTINO', 'N');
INSERT INTO JOGA VALUES ('CRUZEIRO', 'AMERICA MG', 'N');
INSERT INTO JOGA VALUES ('SANTOS', 'CORINTHIANS', 'S');
INSERT INTO JOGA VALUES ('CORINTHIANS', 'SAO PAULO', 'S');
INSERT INTO JOGA VALUES ('BAHIA', 'SPORT', 'N');

-- PALMEIRAS x CORINTHIANS
INSERT INTO PARTIDA VALUES ('PALMEIRAS','CORINTHIANS',TO_DATE('2019/03/10 16:00','YYYY/MM/DD HH24:MI'),'2X1','SAO PAULO');
INSERT INTO PARTIDA VALUES ('PALMEIRAS','CORINTHIANS',TO_DATE('2020/07/05 16:00','YYYY/MM/DD HH24:MI'),'1X1','SAO PAULO');
INSERT INTO PARTIDA VALUES ('PALMEIRAS','CORINTHIANS',TO_DATE('2021/11/15 19:00','YYYY/MM/DD HH24:MI'),'0X2','SAO PAULO');
INSERT INTO PARTIDA VALUES ('PALMEIRAS','CORINTHIANS',TO_DATE('2022/05/03 21:00','YYYY/MM/DD HH24:MI'),'3X0','CAMPINAS');

-- GREMIO x INTERNACIONAL
INSERT INTO PARTIDA VALUES ('GREMIO','INTERNACIONAL',TO_DATE('2019/06/02 17:00','YYYY/MM/DD HH24:MI'),'0X0','PORTO ALEGRE');
INSERT INTO PARTIDA VALUES ('GREMIO','INTERNACIONAL',TO_DATE('2020/08/12 18:00','YYYY/MM/DD HH24:MI'),'2X2','PORTO ALEGRE');
INSERT INTO PARTIDA VALUES ('GREMIO','INTERNACIONAL',TO_DATE('2021/04/18 16:00','YYYY/MM/DD HH24:MI'),'1X0','PORTO ALEGRE');
INSERT INTO PARTIDA VALUES ('GREMIO','INTERNACIONAL',TO_DATE('2022/10/09 19:00','YYYY/MM/DD HH24:MI'),'1X3','PORTO ALEGRE');

-- FLAMENGO x BOTAFOGO
INSERT INTO PARTIDA VALUES ('FLAMENGO','BOTAFOGO',TO_DATE('2019/05/20 16:00','YYYY/MM/DD HH24:MI'),'2X2','RIO DE JANEIRO');
INSERT INTO PARTIDA VALUES ('FLAMENGO','BOTAFOGO',TO_DATE('2020/08/25 18:00','YYYY/MM/DD HH24:MI'),'3X1','RIO DE JANEIRO');
INSERT INTO PARTIDA VALUES ('FLAMENGO','BOTAFOGO',TO_DATE('2021/03/11 20:00','YYYY/MM/DD HH24:MI'),'1X0','RIO DE JANEIRO');
INSERT INTO PARTIDA VALUES ('FLAMENGO','BOTAFOGO',TO_DATE('2022/09/15 21:00','YYYY/MM/DD HH24:MI'),'0X1','RIO DE JANEIRO');

-- ATLETICO x CRUZEIRO
INSERT INTO PARTIDA VALUES ('ATLETICO','CRUZEIRO',TO_DATE('2019/03/23 18:00','YYYY/MM/DD HH24:MI'),'0X2','BELO HORIZONTE');
INSERT INTO PARTIDA VALUES ('ATLETICO','CRUZEIRO',TO_DATE('2020/08/20 18:00','YYYY/MM/DD HH24:MI'),'1X1','BELO HORIZONTE');
INSERT INTO PARTIDA VALUES ('ATLETICO','CRUZEIRO',TO_DATE('2021/07/11 20:00','YYYY/MM/DD HH24:MI'),'3X1','BELO HORIZONTE');
INSERT INTO PARTIDA VALUES ('ATLETICO','CRUZEIRO',TO_DATE('2022/09/22 20:00','YYYY/MM/DD HH24:MI'),'1X0','BELO HORIZONTE');

-- FLAMENGO x VASCO (you already have 2)
INSERT INTO PARTIDA VALUES ('VASCO','FLAMENGO',TO_DATE('2021/06/15 18:00','YYYY/MM/DD HH24:MI'),'3X3','RIO DE JANEIRO');
INSERT INTO PARTIDA VALUES ('VASCO','FLAMENGO',TO_DATE('2022/08/21 18:00','YYYY/MM/DD HH24:MI'),'1X0','RIO DE JANEIRO');

-- BAHIA x VITORIA
INSERT INTO PARTIDA VALUES ('BAHIA','VITORIA',TO_DATE('2019/04/14 16:00','YYYY/MM/DD HH24:MI'),'1X1','SALVADOR');
INSERT INTO PARTIDA VALUES ('BAHIA','VITORIA',TO_DATE('2020/08/12 18:00','YYYY/MM/DD HH24:MI'),'2X0','SALVADOR');
INSERT INTO PARTIDA VALUES ('BAHIA','VITORIA',TO_DATE('2021/05/30 18:00','YYYY/MM/DD HH24:MI'),'0X1','SALVADOR');
INSERT INTO PARTIDA VALUES ('BAHIA','VITORIA',TO_DATE('2022/09/05 18:00','YYYY/MM/DD HH24:MI'),'2X2','SALVADOR');